@startuml
interface Attachment as "Вложение" {
    +тип: ТипВложения
    +путьФайловойСистемы: ПутьФайловойСистемы
    +отображаемоеНазвание: Строка
}

enum AttachmentType as "ТипВложения" {
    ФАЙЛ
    ИЗОБРАЖЕНИЕ
}

class PendingAttachment as "ОжидающееВложение" {
}

class ProjectAttachment as "ВложениеПроекта" {
    +относительныйПуть: ОтносительныйПуть
}

class InvalidProjectAttachment as "НевалидноеВложениеПроекта" {
    +относительныйПуть: ОтносительныйПуть
}

class MessageBody as "КраткаяЗаметка" {
    +текст: Строка
    +вложения: Список<Вложение>
    +ссылки: Список<Строка>
    +заметка: Заметка
}

interface TextState as "СостояниеТекста" {
    +текст: CharSequence
    +выделениеТекста: ВыделениеТекста
    +состояниеОтмены: СостояниеОтменыТекста
    +редактировать(блок: ИзменяемоеСостояниеТекста.() -> Unit)
    +установитьТекстИПоместитьКурсорВКонец(текст: Строка)
}

class TextSelection as "ВыделениеТекста" {
    +начало: Число
    +конец: Число
    +свернуто(): Булев
    +мин(): Число
    +макс(): Число
    +длина(): Число
}

interface TextUndoState as "СостояниеОтменыТекста" {
    +можноОтменить: Булев
    +можноПовторить: Булев
    +отменить()
    +повторить()
    +очиститьИсторию()
}

interface MutableTextState as "ИзменяемоеСостояниеТекста" {
    +исходныйТекст: CharSequence
    +выделениеТекста: ВыделениеТекста
    +длина: Число
    +заменить(начало: Число, конец: Число, текст: Строка)
    +вставить(индекс: Число, текст: Строка)
    +добавитьВКонец(текст: Строка)
    +поместитьКурсорПослеСимволаНа(индекс: Число)
}

class FrontMatter as "Метаданные" {
    +поля: Словарь<Строка, ЗначениеМетаданных>
    +созданоВ(): Строка?
    +метки(): Список<Строка>
    +получить(ключ: Строка): ЗначениеМетаданных?
    +вСтрокуМеток(): Строка
    +вСозданоВМиллисекундах(): ДлинноеЧисло?
    +сПолем(ключ: Строка, значение: ЗначениеМетаданных): Метаданные
    +сНовымКлючом(старыйКлюч: Строка, новыйКлюч: Строка): Метаданные
    +сМеткой(метка: Строка): Метаданные
    +безМетки(метка: Строка): Метаданные
    +безПоля(ключ: Строка): Метаданные
    +вСтроку(): Строка
}

interface FrontMatterValue as "ЗначениеМетаданных" {
}

class Scalar as "Скаляр" {
    +значение: Строка
}

class StringList as "СписокСтрок" {
    +значения: Список<Строка>
}

class RelativePath as "ОтносительныйПуть" {
    +значение: Строка
    +получитьЧасти(): Список<Строка>
    +добавить(путь: ОтносительныйПуть): ОтносительныйПуть
    +название(): Строка
    +родитель(): ОтносительныйПуть
}

class Project as "Проект" {
    +название: Строка
    +корневойПуть: ПутьФайловойСистемы
    +путьЗаметок: ОтносительныйПуть
    +путьРесурсов: ОтносительныйПуть
}

class ProjectFile as "ФайлПроекта" {
    +путьФайловойСистемы: ПутьФайловойСистемы
    +относительныйПуть: ОтносительныйПуть
}

interface SpanInfo as "Токен" {
    +диапазон: ДиапазонТекста
}

class TextRange as "ДиапазонТекста" {
    +начало: Число
    +конец: Число
}

class Heading as "Заголовок" {
    +уровень: Число
}

class Bold as "Жирный" {
}

class Italic as "Курсив" {
}

class CodeInline as "ВстроенныйКод" {
}

class CodeBlock as "БлокКода" {
}

class Image as "Изображение" {
    +содержание: Строка
}

class Link as "Ссылка" {
    +содержание: Строка
    +метка: Строка
    +диапазонСодержания: ДиапазонТекста
    +диапазонМетки: ДиапазонТекста
    +типСсылки(): ТипСсылка
}

enum LinkType as "ТипСсылка" {
    ФАЙЛ
    ЗАМЕТКА
    HTTP
}

class ListItem as "ЭлементСписка" {
}

class Blockquote as "Цитата" {
}

class Note as "Заметка" {
    +имя: Строка
    +файлПроекта: ФайлПроекта
    +последнееИзменение: ДлинноеЧисло
    +созданоВ: ДлинноеЧисло?
    +метки: Список<Строка>?
    +тело: Строка?
}

class Settings as "Настройки" {
    +обратныйМакет: Булев
    +сервис: ВалидныйСервисСинхронизации
    +yandexOAuthТокен: Строка
}

enum ValidSyncProvider as "ВалидныйСервисСинхронизации" {
    ОТСУТСТВУЕТ
    ЯНДЕКС
}

class SearchQuery as "ПоисковойЗапрос" {
    +терминыТела: Список<Строка>
    +исключенныеТерминыТела: Список<Строка>
    +фильтрыМеток: Список<Строка>
    +исключенныеФильтрыМеток: Список<Строка>
    +фильтрИмени: Строка?
    +отрицаемыйФильтрИмени: Строка?
    +сортировкаПо: СортировкаПо
    +сначалаЗакрепленные: Булев
    +построитьFtsЗапросСовпадения(): Строка?
}

enum SortBy as "СортировкаПо" {
    ПОСЛЕДНЕЕ_ИЗМЕНЕНИЕ
    СОЗДАНО_В
}

class LinkPreview as "ИнформацияСсылка" {
    +url: Строка
    +заголовок: Строка?
    +описание: Строка?
    +urlИзображения: Строка?
}

class FileSystemPath as "ПутьФайловойСистемы" {
    +значение: Строка
}

Attachment <|.[norank]. PendingAttachment
Attachment <|.[norank]. ProjectAttachment
Attachment <|.[norank]. InvalidProjectAttachment
Attachment "1" *-[norank]- "1" FileSystemPath
Attachment "1" *-[norank]- "1" AttachmentType
ProjectAttachment "1" *-[norank]- "1" RelativePath
InvalidProjectAttachment "1" *-[norank]- "1" RelativePath

MessageBody "1" o-[norank]- "*" Attachment
MessageBody "1" o-[norank]- "1" Note

TextState "1" *-[norank]- "1" TextSelection
TextState "1" *-[norank]- "1" TextUndoState
TextState .[norank].> MutableTextState
MutableTextState "1" *-[norank]- "1" TextSelection

FrontMatter "1" *-[norank]- "*" FrontMatterValue
FrontMatterValue <|.[norank]. Scalar
FrontMatterValue <|.[norank]. StringList

Project "1" *-[norank]- "1" FileSystemPath
Project "1" *-[norank]- "1" RelativePath : путьЗаметок
Project "1" *-[norank]- "1" RelativePath : путьРесурсов

ProjectFile "1" *-[norank]- "1" FileSystemPath
ProjectFile "1" *-[norank]- "1" RelativePath
SpanInfo "1" *-[norank]- "1" TextRange
SpanInfo <|.[norank]. Heading
SpanInfo <|.[norank]. Bold
SpanInfo <|.[norank]. Italic
SpanInfo <|.[norank]. CodeInline
SpanInfo <|.[norank]. CodeBlock
SpanInfo <|.[norank]. Image
SpanInfo <|.[norank]. ListItem
SpanInfo <|.[norank]. Blockquote
SpanInfo <|.[norank]. Link
Link "1" *-[norank]- "1" TextRange : диапазонСодержания
Link "1" *-[norank]- "1" TextRange : диапазонМетки
Link "1" *-[norank]- "1" LinkType

Note "1" *-[norank]- "1" ProjectFile

Settings "1" *-[norank]- "1" ValidSyncProvider
SearchQuery "1" *-[norank]- "1" SortBy

interface ProjectRepository as "РепозиторийПроекта" {
    +получитьЗаметки(проект: Проект, запрос: ПоисковойЗапрос, включитьТекст: Булев, включитьМетаданные: Булев): Список<Заметка>
    +получитьЗаметкиПостранично(проект: Проект, запрос: ПоисковойЗапрос, включитьТекст: Булев, включитьМетаданные: Булев): Flow<PagingData<Заметка>>
    +получитьЗаметку(проект: Проект, путь: ОтносительныйПуть, включитьТекст: Булев, включитьМетаданные: Булев): Заметка
    +построитьПроект(путьПроекта: ПутьФайловойСистемы): Проект
    +синхронизироватьБазуДанных(проект: Проект)
    +копироватьИзФайловойСистемы(проект: Проект, изПути: ПутьФайловойСистемы, вПутьКаталога: ОтносительныйПуть): ФайлПроекта
    +получитьВсеМетки(проект: Проект): Список<Строка>
    +записатьФайл(проект: Проект, путь: ОтносительныйПуть, байты: ByteArray, стратегия: СтратегияСуществования, создатьРодителей: Булев): ФайлПроекта
    +удалитьФайл(проект: Проект, путь: ОтносительныйПуть)
    +копироватьФайл(проект: Проект, путь: ОтносительныйПуть, новыйПуть: ОтносительныйПуть, стратегия: СтратегияСуществования, создатьРодителей: Булев): ФайлПроекта
    +переместитьФайл(проект: Проект, путь: ОтносительныйПуть, новыйПуть: ОтносительныйПуть, стратегия: СтратегияСуществования, создатьРодителей: Булев): ФайлПроекта
    +прочитатьФайл(проект: Проект, путь: ОтносительныйПуть): ByteArray
    +получитьСписокФайловПроекта(проект: Проект): Список<ФайлПроекта>
    +получитьФайлПроекта(проект: Проект, путь: ОтносительныйПуть): ФайлПроекта
}

enum FileExistsStrategy as "СтратегияСуществования" {
    ПЕРЕЗАПИСАТЬ
    АВТО_ПЕРЕИМЕНОВАНИЕ
}

class AndroidProjectRepository as "РепозиторийAndroidПроекта" {
    +projectDao: DaoПроекта
    +noteDao: DaoЗаметок
}

interface SettingsRepository as "РепозиторийНастроек" {
    +установитьНастройки(проект: Проект, настройки: Настройки): Настройки
    +получитьНастройки(проект: Проект): Настройки
    +установитьПутьПроекта(путь: ПутьФайловойСистемы)
    +получитьПутьПроекта(): ПутьФайловойСистемы?
}

class AndroidSettingsRepository as "РепозиторийAndroidНастроек" {
}

interface LinkPreviewRepository as "РепозиторийИнформацияСсылка" {
    +получитьИнформацияСсылка(url: Строка): ИнформацияСсылка?
}

class AndroidLinkPreviewRepository as "РепозиторийAndroidИнформацияСсылка" {
    +linkPreviewDao: DaoИнформацияСсылка
}

interface SyncRepository as "РепозиторийСинхронизации" {
    +скачатьФайл(путь: ОтносительныйПуть): ByteArray?
    +загрузитьФайл(путь: ОтносительныйПуть, байты: ByteArray)
    +удалитьФайл(путь: ОтносительныйПуть)
}

class YandexSyncRepository as "РепозиторийYandexСинхронизации" {
    +oauthToken: Строка
}

class SyncRepositoryFactory as "ФабрикаРепозиторияСинхронизации" {
    +создать(настройки: Настройки): РепозиторийСинхронизации?
}

abstract class NoteDb as "DbЗаметок" {
    +projectDao(): DaoПроекта
    +noteDao(): DaoЗаметок
    +linkPreviewDao(): DaoИнформацияСсылка
}

interface NoteDao as "DaoЗаметок" {
    +вставитьЗаметку(заметка: СущностьЗаметка): ДлинноеЧисло
    +удалитьПоUri(uri: Строка)
    +получитьЗаметкуПоUri(uri: Строка): СущностьЗаметка?
    +поискЗаметок(запрос: SupportSQLiteQuery): Список<СущностьЗаметка>
    +поискЗаметокПостранично(запрос: SupportSQLiteQuery): PagingSource<Число, СущностьЗаметка>
    +получитьВсеМетки(идентификаторПроекта: ДлинноеЧисло): Список<Строка>
}

interface ProjectDao as "DaoПроекта" {
    +вставитьПроект(проект: СущностьПроекта): ДлинноеЧисло
    +получитьИдентификаторПроекта(корневойПуть: Строка): ДлинноеЧисло?
}

interface LinkPreviewDao as "DaoИнформацияСсылка" {
    +получитьПоUrl(url: Строка): СущностьИнформацияСсылка?
    +вставить(сущность: СущностьИнформацияСсылка)
}

class NoteEntity as "СущностьЗаметка" {
    +id: ДлинноеЧисло
    +идентификаторПроекта: ДлинноеЧисло
    +uri: Строка
    +название: Строка
    +последнееИзменение: ДлинноеЧисло
    +созданоВ: ДлинноеЧисло?
    +метки: Строка
    +тело: Строка
}

class NoteEntityFts as "СущностьЗаметкиFts" {
    +id: ДлинноеЧисло
    +название: Строка
    +тело: Строка
}

class ProjectEntity as "СущностьПроекта" {
    +id: ДлинноеЧисло
    +название: Строка
    +корневойПуть: Строка
}

class LinkPreviewEntity as "СущностьИнформацияСсылка" {
    +url: Строка
    +заголовок: Строка?
    +описание: Строка?
    +urlИзображения: Строка?
    +полученоВ: ДлинноеЧисло
}

AndroidProjectRepository .[norank].|> ProjectRepository
AndroidSettingsRepository .[norank].|> SettingsRepository
AndroidLinkPreviewRepository .[norank].|> LinkPreviewRepository
YandexSyncRepository .[norank].|> SyncRepository
YandexSyncRepository <.. SyncRepositoryFactory

NoteDb "1" *-[norank]- "1" NoteDao
NoteDb "1" *-[norank]- "1" ProjectDao
NoteDb "1" *-[norank]- "1" LinkPreviewDao

AndroidProjectRepository "1" o-[norank]- "1" NoteDao
AndroidProjectRepository "1" o-[norank]- "1" ProjectDao
AndroidLinkPreviewRepository "1" o-[norank]- "1" LinkPreviewDao

NoteDao .[norank].> NoteEntity
ProjectDao .[norank].> ProjectEntity
LinkPreviewDao .[norank].> LinkPreviewEntity
NoteEntityFts .[norank].> NoteEntity

SyncRepositoryFactory .[norank].> SyncRepository

LinkPreviewRepository .[norank].> LinkPreview

ProjectRepository .[norank].> FileExistsStrategy
ProjectRepository .[norank].> SearchQuery
ProjectRepository .[norank].> Project
ProjectRepository .[norank].> Note
ProjectRepository .[norank].> RelativePath
ProjectRepository .[norank].> ProjectFile
ProjectRepository .[norank].> FileSystemPath

SettingsRepository .[norank].> Settings
SettingsRepository .[norank].> Project

SyncRepository .[norank].> RelativePath

interface UseCase as "UC<Вход, Выход>" {
    +invoke(вход: Вход): Выход
}

interface FlowUseCase as "FlowUC<Вход, Выход>" {
    +invoke(вход: Вход): Flow<Выход>
}

class SendNoteInput as "ВходОтправитьЗаметку" {
    +проект: Проект
    +тело: Строка
    +вложения: Список<Вложение>
    +редактируемаяЗаметка: Заметка?
}

class SendNoteUseCase as "ОтправитьЗаметкуUC<ВходОтправитьЗаметку, Unit>" {
    +репозиторийПроекта: РепозиторийПроекта
    +создатьЗаметкуUC: СоздатьЗаметкуUC
    +копироватьВРесурсыUC: КопироватьВРесурсыUC
    +сохранитьТекстЗаметкиUC: СохранитьТекстЗаметкиUC
}

class GetMessagesInput as "ВходПолучитьСообщения" {
    +проект: Проект
}

class GetMessagesUseCase as "ПолучитьСообщенияUC<ВходПолучитьСообщения, Flow<PagingData<КраткаяЗаметка>>>" {
    +репозиторийПроекта: РепозиторийПроекта
    +получитьФайлПроектаUC: ПолучитьФайлПроектаUC
}

class GetNotesInput as "ВходПолучитьЗаметки" {
    +проект: Проект
    +строкаПоисковогоЗапроса: Строка
}

class GetNotesUseCase as "ПолучитьЗаметкиUC<ВходПолучитьЗаметки, Flow<PagingData<Заметка>>>" {
    +репозиторийПроекта: РепозиторийПроекта
}

class GetPinnedMessagesInput as "ВходПолучитьЗакрепленныеСообщения" {
    +проект: Проект
}

class GetPinnedMessagesUseCase as "ПолучитьЗакрепленныеСообщенияUC<ВходПолучитьЗакрепленныеСообщения, Список<КраткаяЗаметка>>" {
    +репозиторийПроекта: РепозиторийПроекта
    +получитьФайлПроектаUC: ПолучитьФайлПроектаUC
}

class CreateNoteInput as "ВходСоздатьЗаметку" {
    +проект: Проект
    +название: Строка
    +метки: Список<Строка>
    +начальныйТекст: Строка
    +включитьТекст: Булев
    +включитьМетаданные: Булев
}

class CreateNoteUseCase as "СоздатьЗаметкуUC<ВходСоздатьЗаметку, Заметка>" {
    +репозиторийПроекта: РепозиторийПроекта
    +получитьЗаметкуUC: ПолучитьЗаметкуUC
}

class ToggleNoteTagInput as "ВходПереключитьМеткуЗаметки" {
    +проект: Проект
    +заметка: Заметка
    +метка: Строка
}

class ToggleNoteTagUseCase as "ПереключитьМеткуЗаметкиUC<ВходПереключитьМеткуЗаметки, Метаданные>" {
    +репозиторийПроекта: РепозиторийПроекта
}

class RenameNoteInput as "ВходПереименоватьЗаметку" {
    +проект: Проект
    +заметка: Заметка
    +новоеНазвание: Строка
    +включитьТекст: Булев
    +включитьМетаданные: Булев
}

class RenameNoteUseCase as "ПереименоватьЗаметкуUC<ВходПереименоватьЗаметку, Заметка>" {
    +репозиторийПроекта: РепозиторийПроекта
    +получитьЗаметкуUC: ПолучитьЗаметкуUC
}

class GetNoteInput as "ВходПолучитьЗаметку" {
    +проект: Проект
    +относительныйПуть: ОтносительныйПуть
    +включитьТекст: Булев
    +включитьМетаданные: Булев
}

class GetNoteUseCase as "ПолучитьЗаметкуUC<ВходПолучитьЗаметку, Заметка>" {
    +репозиторийПроекта: РепозиторийПроекта
}

class SaveNoteTextInput as "ВходСохранитьТекстЗаметки" {
    +проект: Проект
    +заметка: Заметка
    +текст: Строка
}

class SaveNoteTextUseCase as "СохранитьТекстЗаметкиUC<ВходСохранитьТекстЗаметки, Unit>" {
    +репозиторийПроекта: РепозиторийПроекта
}

class DeleteNoteInput as "ВходУдалитьЗаметку" {
    +проект: Проект
    +заметка: Заметка
}

class DeleteNoteUseCase as "УдалитьЗаметкуUC<ВходУдалитьЗаметку, Unit>" {
    +репозиторийПроекта: РепозиторийПроекта
}

class GetRealSpanInfoLinkTypeInput as "ВходПолучитьРеальныйТипСсылкиТокена" {
    +проект: Проект
    +токен: Ссылка
}

class GetRealSpanInfoLinkTypeUseCase as "ПолучитьРеальныйТипСсылкиТокенаUC<ВходПолучитьРеальныйТипСсылкиТокена, ТипСсылка>" {
    +получитьФайлПроектаUC: ПолучитьФайлПроектаUC
}

class ApplyEditorEventInput as "ВходПрименитьСобытиеРедактора" {
    +проект: Проект
    +состояние: СостояниеТекста
    +событие: EditorEvent
}

class ApplyEditorEventUseCase as "ПрименитьСобытиеРедактораUC<ВходПрименитьСобытиеРедактора, Unit>" {
    +копироватьВРесурсыUC: КопироватьВРесурсыUC
}

class SyncProjectInput as "ВходСинхронизироватьПроект" {
    +проект: Проект
    +настройки: Настройки
}

class SyncProjectUseCase as "СинхронизироватьПроектUC<ВходСинхронизироватьПроект, Unit>" {
    +репозиторийПроекта: РепозиторийПроекта
    +фабрикаРепозиторияСинхронизации: ФабрикаРепозиторияСинхронизации
}

class SelectProjectInput as "ВходВыбратьПроект" {
    +путьПроекта: ПутьФайловойСистемы
}

class SelectProjectUseCase as "ВыбратьПроектUC<ВходВыбратьПроект, Проект>" {
    +репозиторийПроекта: РепозиторийПроекта
    +репозиторийНастроек: РепозиторийНастроек
}

class LoadSavedProjectUseCase as "ЗагрузитьСохраненныйПроектUC<Unit, Проект?>" {
    +репозиторийПроекта: РепозиторийПроекта
    +репозиторийНастроек: РепозиторийНастроек
}

class GetSettingsInput as "ВходПолучитьНастройки" {
    +проект: Проект
}

class GetSettingsUseCase as "ПолучитьНастройкиUC<ВходПолучитьНастройки, Настройки>" {
    +репозиторийНастроек: РепозиторийНастроек
}

class SetSettingsInput as "ВходУстановитьНастройки" {
    +проект: Проект
    +новыеНастройки: Настройки
}

class SetSettingsUseCase as "УстановитьНастройкиUC<ВходУстановитьНастройки, Настройки>" {
    +репозиторийНастроек: РепозиторийНастроек
}

class GetAllTagsInput as "ВходПолучитьВсеМетки" {
    +проект: Проект
}

class GetAllTagsUseCase as "ПолучитьВсеМеткиUC<ВходПолучитьВсеМетки, Список<Строка>>" {
    +репозиторийПроекта: РепозиторийПроекта
}

class SyncDatabaseInput as "ВходСинхронизироватьБазуДанных" {
    +проект: Проект
}

class SyncDatabaseUseCase as "СинхронизироватьБазуДанныхUC<ВходСинхронизироватьБазуДанных, Unit>" {
    +репозиторийПроекта: РепозиторийПроекта
}

class GetLinkPreviewInput as "ВходПолучитьИнформацияСсылка" {
    +url: Строка
}

class GetLinkPreviewUseCase as "ПолучитьИнформацияСсылкаUC<ВходПолучитьИнформацияСсылка, ИнформацияСсылка?>" {
    +linkPreviewRepository: LinkPreviewRepository
}

class ApplySearchEventInput as "ВходПрименитьСобытиеПоиска" {
    +состояние: СостояниеТекста
    +событие: SearchEvent
}

class ApplySearchEventUseCase as "ПрименитьСобытиеПоискаUC<ВходПрименитьСобытиеПоиска, Unit>" {
}

class CopyToAssetsInput as "ВходКопироватьВРесурсы" {
    +проект: Проект
    +путьРесурса: ПутьФайловойСистемы
}

class CopyToAssetsUseCase as "КопироватьВРесурсыUC<ВходКопироватьВРесурсы, ФайлПроекта>" {
    +репозиторийПроекта: РепозиторийПроекта
}

class GetProjectFileInput as "ВходПолучитьФайлПроекта" {
    +проект: Проект
    +относительныйПуть: ОтносительныйПуть
}

class GetProjectFileUseCase as "ПолучитьФайлПроектаUC<ВходПолучитьФайлПроекта, ФайлПроекта>" {
    +репозиторийПроекта: РепозиторийПроекта
}

FlowUseCase <|.[norank]. GetMessagesUseCase
GetMessagesUseCase .[norank].> GetMessagesInput
GetMessagesUseCase "1" o-[norank]- "1" ProjectRepository
GetMessagesUseCase "1" o-[norank]- "1" GetProjectFileUseCase

FlowUseCase <|.[norank]. GetNotesUseCase
GetNotesUseCase .[norank].> GetNotesInput
GetNotesUseCase "1" o-[norank]- "1" ProjectRepository

UseCase <|.[norank]. SendNoteUseCase
SendNoteUseCase .[norank].> SendNoteInput
SendNoteUseCase "1" o-[norank]- "1" ProjectRepository
SendNoteUseCase "1" o-[norank]- "1" CreateNoteUseCase
SendNoteUseCase "1" o-[norank]- "1" CopyToAssetsUseCase
SendNoteUseCase "1" o-[norank]- "1" SaveNoteTextUseCase

UseCase <|.[norank]. GetPinnedMessagesUseCase
GetPinnedMessagesUseCase .[norank].> GetPinnedMessagesInput
GetPinnedMessagesUseCase "1" o-[norank]- "1" ProjectRepository
GetPinnedMessagesUseCase "1" o-[norank]- "1" GetProjectFileUseCase

UseCase <|.[norank]. CreateNoteUseCase
CreateNoteUseCase .[norank].> CreateNoteInput
CreateNoteUseCase "1" o-[norank]- "1" ProjectRepository
CreateNoteUseCase "1" o-[norank]- "1" GetNoteUseCase

UseCase <|.[norank]. ToggleNoteTagUseCase
ToggleNoteTagUseCase .[norank].> ToggleNoteTagInput
ToggleNoteTagUseCase "1" o-[norank]- "1" ProjectRepository

UseCase <|.[norank]. RenameNoteUseCase
RenameNoteUseCase .[norank].> RenameNoteInput
RenameNoteUseCase "1" o-[norank]- "1" ProjectRepository
RenameNoteUseCase "1" o-[norank]- "1" GetNoteUseCase

UseCase <|.[norank]. GetNoteUseCase
GetNoteUseCase .[norank].> GetNoteInput
GetNoteUseCase "1" o-[norank]- "1" ProjectRepository

UseCase <|.[norank]. SaveNoteTextUseCase
SaveNoteTextUseCase .[norank].> SaveNoteTextInput
SaveNoteTextUseCase "1" o-[norank]- "1" ProjectRepository

UseCase <|.[norank]. DeleteNoteUseCase
DeleteNoteUseCase .[norank].> DeleteNoteInput
DeleteNoteUseCase "1" o-[norank]- "1" ProjectRepository

UseCase <|.[norank]. GetRealSpanInfoLinkTypeUseCase
GetRealSpanInfoLinkTypeUseCase .[norank].> GetRealSpanInfoLinkTypeInput
GetRealSpanInfoLinkTypeUseCase "1" o-[norank]- "1" GetProjectFileUseCase

UseCase <|.[norank]. ApplyEditorEventUseCase
ApplyEditorEventUseCase .[norank].> ApplyEditorEventInput
ApplyEditorEventUseCase "1" o-[norank]- "1" CopyToAssetsUseCase

UseCase <|.[norank]. SyncProjectUseCase
SyncProjectUseCase .[norank].> SyncProjectInput
SyncProjectUseCase "1" o-[norank]- "1" ProjectRepository
SyncProjectUseCase "1" o-[norank]- "1" SyncRepositoryFactory

UseCase <|.[norank]. SelectProjectUseCase
SelectProjectUseCase .[norank].> SelectProjectInput
SelectProjectUseCase "1" o-[norank]- "1" ProjectRepository
SelectProjectUseCase "1" o-[norank]- "1" SettingsRepository

UseCase <|.[norank]. LoadSavedProjectUseCase
LoadSavedProjectUseCase "1" o-[norank]- "1" ProjectRepository
LoadSavedProjectUseCase "1" o-[norank]- "1" SettingsRepository

UseCase <|.[norank]. GetSettingsUseCase
GetSettingsUseCase .[norank].> GetSettingsInput
GetSettingsUseCase "1" o-[norank]- "1" SettingsRepository

UseCase <|.[norank]. SetSettingsUseCase
SetSettingsUseCase .[norank].> SetSettingsInput
SetSettingsUseCase "1" o-[norank]- "1" SettingsRepository

UseCase <|.[norank]. GetAllTagsUseCase
GetAllTagsUseCase .[norank].> GetAllTagsInput
GetAllTagsUseCase "1" o-[norank]- "1" ProjectRepository

UseCase <|.[norank]. SyncDatabaseUseCase
SyncDatabaseUseCase .[norank].> SyncDatabaseInput
SyncDatabaseUseCase "1" o-[norank]- "1" ProjectRepository

UseCase <|.[norank]. CopyToAssetsUseCase
CopyToAssetsUseCase .[norank].> CopyToAssetsInput
CopyToAssetsUseCase "1" o-[norank]- "1" ProjectRepository

UseCase <|.[norank]. GetLinkPreviewUseCase
GetLinkPreviewUseCase .[norank].> GetLinkPreviewInput
GetLinkPreviewUseCase "1" o-[norank]- "1" LinkPreviewRepository

UseCase <|.[norank]. ApplySearchEventUseCase
ApplySearchEventUseCase .[norank].> ApplySearchEventInput

UseCase <|.[norank]. GetProjectFileUseCase
GetProjectFileUseCase .[norank].> GetProjectFileInput

class MarkdownParser as "MarkdownОбработчик" {
    +получитьТокены(текст: Строка): Список<Токен>
    +удалитьВложения(текст: Строка, токены: Список<Токен>): Строка
}

MarkdownParser .[norank].> SpanInfo

@enduml