@startuml
skinparam ClassBackgroundColor #FFFFFF

!include class-diagram.puml

'SpanInfo
remove SpanInfo
remove Heading
remove Bold
remove Italic
remove Image
remove Link
remove LinkType
remove TextRange
remove CodeInline
remove CodeBlock
remove Blockquote
remove ListItem

'FrontMatter
remove FrontMatter
remove FrontMatterValue
remove Scalar
remove StringList

'TextState
remove TextState
remove MutableTextState
remove TextSelection
remove TextUndoState

'Settings
'remove Settings
'remove ValidSyncProvider

'Project
'remove Project
'remove RelativePath
'remove FileSystemPath
'remove ProjectFile
remove Attachment
remove AttachmentType
remove ProjectAttachment
remove InvalidProjectAttachment
remove PendingAttachment
remove MessageBody
'remove Note

'SearchQuery
'remove SearchQuery
'remove SortBy

'LinkPreview
'remove LinkPreview

'Repositories
'remove ProjectRepository
'remove AndroidProjectRepository
'remove NoteDao
'remove ProjectDao
'remove LinkPreviewDao
'remove NoteEntity
'remove NoteEntityFts
'remove ProjectEntity
'remove FileExistsStrategy
'remove LinkPreviewEntity
remove NoteDb
'remove LinkPreviewRepository
'remove AndroidLinkPreviewRepository
'remove SyncRepository
'remove YandexSyncRepository
'remove SyncRepositoryFactory
'remove SettingsRepository
'remove AndroidSettingsRepository

'UseCases
remove UseCase
remove FlowUseCase
remove GetMessagesUseCase
remove CreateNoteUseCase
remove CreateNoteInput
remove ApplyEditorEventInput
remove GetRealSpanInfoLinkTypeUseCase
remove GetPinnedMessagesUseCase
remove ToggleNoteTagUseCase
remove SyncProjectUseCase
remove ApplyEditorEventUseCase
remove SendNoteInput
remove DeleteNoteUseCase
remove DeleteNoteInput
remove GetNoteInput
remove GetNoteUseCase
remove RenameNoteUseCase
remove CopyToAssetsUseCase
remove SaveNoteTextUseCase
remove GetAllTagsUseCase
remove SelectProjectInput
remove SyncDatabaseInput
remove SendNoteUseCase
remove SyncDatabaseUseCase
remove LoadSavedProjectUseCase
remove GetSettingsUseCase
remove SelectProjectUseCase
remove SetSettingsUseCase
remove SetSettingsInput
remove GetLinkPreviewUseCase
remove GetLinkPreviewInput
remove GetMessagesInput
remove GetPinnedMessagesInput
remove ToggleNoteTagInput
remove RenameNoteInput
remove SaveNoteTextInput
remove GetRealSpanInfoLinkTypeInput
remove SyncProjectInput
remove GetSettingsInput
remove GetAllTagsInput
remove ApplySearchEventUseCase
remove ApplySearchEventInput
remove CopyToAssetsInput
remove GetNotesUseCase
remove GetNotesInput
remove GetProjectFileUseCase
remove GetProjectFileInput

'MarkdownParser
remove MarkdownParser

RelativePath -[hidden]- Project
FileSystemPath -[hidden]r- RelativePath
Note -[hidden]r- ProjectFile

@enduml