@startuml

!theme plain

hide empty methods

!procedure $schema($name, $slug)
package "$name" as $slug <<Rectangle>>
!endprocedure

!procedure $table($name, $slug)
entity "<b>$name</b>" as $slug << (T, White) table >>
!endprocedure

!procedure $view($name, $slug)
entity "<b>$name</b>" as $slug << (V, Aquamarine) view >>
!endprocedure

!procedure $pk($name)
<color:#GoldenRod><&key></color> <b>$name</b>
!endprocedure

!procedure $fk($name)
<color:#Silver><&key></color> $name
!endprocedure

!procedure $column($name)
{field} <color:#White><&media-record></color> $name
!endprocedure

$table("Проект", "t_project") {
  $pk("id"): INTEGER NOT NULL
  $column("название"): TEXT NOT NULL
  $column("корневойПуть"): TEXT NOT NULL UNIQUE
}

$table("Заметка", "t_note") {
  $pk("id"): INTEGER NOT NULL
  $fk("проектId"): INTEGER NOT NULL
  $column("uri"): TEXT NOT NULL UNIQUE
  $column("название"): TEXT NOT NULL
  $column("последнееИзменение"): INTEGER NOT NULL
  $column("созданоВ"): INTEGER
  $column("метки"): TEXT NOT NULL
  $column("тело"): TEXT NOT NULL
}

$table("ЗаметкаFts", "t_note_fts") {
  $fk("rowid"): INTEGER NOT NULL
  $column("название"): TEXT
  $column("тело"): TEXT
}

$table("СсылкаИнфо", "t_link_preview") {
  $pk("url"): TEXT NOT NULL
  $column("заголовок"): TEXT
  $column("описание"): TEXT
  $column("urlИзображения"): TEXT
  $column("полученоВ"): INTEGER NOT NULL
}

t_project::id ||-right-o{ t_note::проектId : содержит
t_note::id ||-down-|| t_note_fts::rowid : ссылается
t_project::id ||-[hidden]down-|| t_link_preview::url

@enduml
