@startuml
skinparam style strictuml
skinparam sequenceMessageAlign center

actor "Пользователь" as User
participant "NoteSearchBar:\nUI" as UI
participant "DrawerActions:\nDrawerActions" as Actions
participant "ApplySearchEventUseCase:\nUseCase" as SearchUseCase
participant "ComposeTextState:\nTextState" as TextState

User -> UI : Нажатие кнопки "tag:"
activate UI

UI -> Actions : onSearchEvent(\nSearchEvent.AppendTag)
activate Actions

Actions -> SearchUseCase : invoke(\nsearchState, searchEvent)
activate SearchUseCase

SearchUseCase -> TextState : text\n(получение текста)
activate TextState
TextState --> SearchUseCase : CharSequence
deactivate TextState

SearchUseCase -> SearchUseCase : Добавление пробела в\nпрефикс (если нужно)

SearchUseCase -> TextState : edit { ... }
activate TextState

TextState -> TextState : append(prefix + "tag:\"\"")
TextState -> TextState : placeCursorAfterCharAt(\nlength - 2)
TextState --> SearchUseCase : Success
deactivate TextState

SearchUseCase --> Actions : Success
deactivate SearchUseCase

Actions --> UI : Обновление текста\nв TextField
deactivate Actions
deactivate UI

@enduml